dist: trusty

language: c

compiler:
  - gcc

script: tools/scripts/makeall

before_install:
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt-get -q update
  - sudo apt-get install -y gcc-arm-none-eabi
  - sudo apt-get install -y gcc-aarch64-linux-gnu

notifications:
  email:
    recipients:
      - jcd@tribudubois.net
    on_success: change
    on_failure: always
