dist: bionic

language: c

compiler:
  - gcc

script: tools/scripts/makeall

before_install:
  - sudo apt-get -q update
  - sudo apt-get install -y gcc-8-aarch64-linux-gnu
  - sudo apt-get install -y gcc-8-arm-linux-gnueabi
  - sudo apt-get install -y gcc-8-riscv64-linux-gnu
  - sudo apt-get install -y gcc-8

notifications:
  email:
    on_success: always
    on_failure: always
