dist: trusty

language: c

compiler:
  - gcc

script: tools/scripts/makeall

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gcc-4.9-arm-linux-gnueabihf
  - sudo apt-get install -y gcc-4.9-aarch64-linux-gnu

notifications:
  email:
    recipients:
      - jcd@tribudubois.net
    on_success: change
    on_failure: always
