dist: bionic

language: c

compiler:
  - gcc

script: tools/scripts/makeall

before_install:
  - sudo apt-get -q update
  - sudo apt-get install -y gcc-aarch64-linux-gnu
  - sudo apt-get install -y gcc-arm-linux-gnueabi
  - sudo apt-get install -y gcc-8-riscv64-linux-gnu
  - sudo apt-get install -y device-tree-compiler
  - sudo apt-get install -y gcc
  - sudo update-alternatives --install /usr/bin/riscv64-linux-gnu-gcc riscv64-linux-gnu-gcc /usr/bin/riscv64-linux-gnu-gcc-8 100 --slave /usr/bin/riscv64-linux-gnu-cpp riscv64-linux-gnu-cpp /usr/bin/riscv64-linux-gnu-cpp-8 --slave /usr/bin/riscv64-linux-gnu-gcc-ar riscv64-linux-gnu-ar /usr/bin/riscv64-linux-gnu-gcc-ar-8 --slave /usr/bin/riscv64-linux-gnu-gcc-nm riscv64-linux-gnu-gcc-nm /usr/bin/riscv64-linux-gnu-gcc-nm-8

notifications:
  email:
    on_success: always
    on_failure: always
